### PR TITLE
Add React ^15.0.0 as an OR'd dependency.

### PR DESCRIPTION
**Pull request by merlinpatt**

### CODE REVIEW

**Comment by Deadarius** [comment]
Any update on this one?

**Comment by merlinpatt** [comment]
@wangzuo any update?

**Comment by woodenconsulting** [comment]
I've published an interim package with these updates [here](https://www.npmjs.com/package/react-input-slider-2) if anyone is interested.

**Comment by wangzuo** [comment]
Thanks, 1.6.0 was released with this fix.

**Pull request merged**
